# Generated by Django 4.0.3 on 2022-12-06 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import graph_constructor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_nodes', models.PositiveIntegerField(default=30, verbose_name='Максимальное количество узлов')),
                ('max_edges', models.PositiveIntegerField(default=50, verbose_name='Максимальное количество ребер')),
                ('can_circle', models.BooleanField(verbose_name='Возможно зацикливание графа')),
            ],
            options={
                'verbose_name': 'Настройки графа',
            },
        ),
        migrations.CreateModel(
            name='UserGraphConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(blank=True, null=True, verbose_name='Контент графа')),
                ('is_active', models.BooleanField(default=False, verbose_name='Текущий граф')),
                ('mark', models.FloatField(blank=True, null=True, verbose_name='Оценка графа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Граф пользователя',
                'verbose_name_plural': 'Графы пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=graph_constructor.models.get_emotion_upload, verbose_name='файл эмоции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Эмоция',
                'verbose_name_plural': 'Эмоции',
            },
        ),
    ]
