# Generated by Django 4.0.3 on 2022-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecuteCodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('request', models.TextField(blank=True, null=True, verbose_name='Запрос')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('status', models.BooleanField(default=True, verbose_name='Статус запроса')),
            ],
            options={
                'verbose_name': 'Лог запуска кода',
                'verbose_name_plural': 'Логи запуска кода',
            },
        ),
        migrations.CreateModel(
            name='UserExecuteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_time', models.FloatField(default=216000, verbose_name='Оставшееся время работы в секундах')),
                ('console_content', models.TextField(blank=True, default=None, null=True, verbose_name='Последний вывод консоли')),
            ],
            options={
                'verbose_name': 'Настройки запуска кода пользователя',
                'verbose_name_plural': 'Настройки запуска кода пользователей',
            },
        ),
    ]
