# Generated by Django 4.0.3 on 2022-12-06 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('graph_constructor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Черновик'), (2, 'Активно'), (3, 'Закрыто')], default=1, verbose_name='Статус задания')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Задание на граф'), (2, 'Ручная проверка'), (3, 'Простой ответ')], default=3, verbose_name='Тип задания')),
                ('auto_check', models.BooleanField(help_text='Автоматическая проверка доступна только для графа', verbose_name='Автоматическая проверка')),
                ('answer', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ответ на задание')),
                ('max_mark', models.FloatField(verbose_name='Оценка за задание')),
                ('graph_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph_constructor.usergraphconstructor', verbose_name='Проверочный граф')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ответ на задание')),
                ('mark', models.FloatField(blank=True, default=None, null=True, verbose_name='Оценка')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'На проверке'), (2, 'Завершено')], default=1, verbose_name='Статус ответа')),
                ('answer_graph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph_constructor.usergraphconstructor', verbose_name='ответ в виде графа')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Ответ на задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
    ]
